// ADD user Profile
export const ADD_PROFILE_API_CALL_START = 'ADD_PROFILE_API_CALL_START';
export const ADD_PROFILE_API_CALL_SUCCESS = 'ADD_PROFILE_API_CALL_SUCCESS';
export const ADD_PROFILE_API_CALL_FAIL = 'ADD_PROFILE_API_CALL_FAIL';
// GET user PROFILE
export const GET_PROFILE_API_CALL_START = 'GET_PROFILE_API_CALL_START';
export const GET_PROFILE_API_CALL_SUCCESS = 'GET_PROFILE_API_CALL_SUCCESS';
export const GET_PROFILE_API_CALL_FAIL = 'GET_PROFILE_API_CALL_FAIL';
export const CLEAR_PROFILE_DATA = 'CLEAR_PROFILE_DATA';
// ADD user data
export const ADD_USER_API_CALL_START = 'ADD_USER_API_CALL_START';
export const ADD_USER_API_CALL_SUCCESS = 'ADD_USER_API_CALL_SUCCESS';
export const ADD_USER_API_CALL_FAIL = 'ADD_USER_API_CALL_FAIL';
export const CLEAR_API_DATA = 'CLEAR_API_DATA';
// DELETE user data
export const DELETE_USER_API_CALL_START = 'DELETE_USER_API_CALL_START';
export const DELETE_USER_API_CALL_SUCCESS = 'DELETE_USER_API_CALL_SUCCESS';
export const DELETE_USER_API_CALL_FAIL = 'DELETE_USER_API_CALL_FAIL';
// UPDATE user data
export const UPDATE_USER_API_CALL_START = 'UPDATE_USER_API_CALL_START';
export const UPDATE_USER_API_CALL_SUCCESS = 'UPDATE_USER_API_CALL_SUCCESS';
export const UPDATE_USER_API_CALL_FAIL = 'UPDATE_USER_API_CALL_FAIL';
// Get user data
export const GET_USER_API_CALL_START = 'GET_USER_API_CALL_START';
export const GET_USERS_API_CALL_SUCCESS = 'GET_USERS_API_CALL_SUCCESS';
export const GET_USER_API_CALL_FAIL = 'GET_USER_API_CALL_FAIL';
// get roles
export const GET_ROLES_API_CALL_START = 'GET_ROLES_API_CALL_START';
export const GET_ROLE_API_CALL_SUCCESS = 'GET_ROLE_API_CALL_SUCCESS';
export const GET_ROLES_API_CALL_FAIL = 'GET_ROLES_API_CALL_FAIL';
//For Auth page
export const AUTH_START="AUTH_START";
export const AUTH_SUCCESS="AUTH_SUCCESS";
export const AUTH_FAILED="AUTH_FAILED";
export const AUTH_LOGOUT="AUTH_LOGOUT";
//For Auth Reset page
export const AUTH_RESET_START="AUTH_RESET_START";
export const AUTH_RESET_SUCCESS="AUTH_RESET_SUCCESS";
export const AUTH_RESET_FAILED="AUTH_RESET_FAILED";
